[build]
  base = "" # Set to the root directory if no subdirectory is needed
  publish = "client/dist" # Ensure this matches the actual build output directory
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
